# This file contains values from Cookiecutter

default_context:
  project_name: "pywipe"
  project_description: "Data Preprocessing Toolkit"
  organization: "Open Source"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.8
  github_name: "Koushik-Dutta-py"
  email: "koushik.dutta.py@protonmail.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "cli"
